"""
Harness test for echo path estimation comparison.

Runs FD_NLMS and CONJUGATE_MDF (hop mode) through the SAME harness engine
(harness.core.runner.run_test — one overlap-save loop, one metric set) so
the two algorithms are compared with only the weight update differing
(their input/output frame geometry is identical by construction).

Ground truth: generated by echo_path_data.py from original_speech.wav —
500 ms path, 45 ms initial delay (720 samples = 5.625 hops: deliberately
NOT hop-aligned, the criterion-cliff regime), RT60 300 ms.

Usage:
    python test_echo_path_comparison.py          # both algorithms
    python test_echo_path_comparison.py fdnlms   # one algorithm
"""

import os
import sys
from typing import Optional

import numpy as np
import soundfile as sf

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from harness import run_test
from harness.core.runner import TestConfig
from harness.adapters import CGMDFAdapter, FDNLMSAdapter
from echo_path_data import load_echo_path_data, compare_echo_paths, \
    print_comparison_report

FFT, STEP, N_G = 512, 128, 64


def run_algorithm(tag, make, ref, mic, true_path, data):
    algo = make()
    cfg = TestConfig(fft_size=FFT, overlap=1.0 - STEP / FFT)
    cfg.true_echo_path = true_path
    result = run_test(algo, ref, mic, config=cfg, algorithm_name=tag)
    print(f"\n{'=' * 60}\n{tag}\n{'=' * 60}")
    for k in ('erle', 'correlation'):
        if k in result.metrics:
            print(f"  {k:14s}: {result.metrics[k]:.4f}")
    if result.echo_path_metrics is not None:
        m = result.echo_path_metrics
        print(f"  path NMSE      : {m.get('nmse_db', float('nan')):.2f} dB")
        print(f"  path delay err : {m.get('delay_error_samples', '?')} samples")
        print(f"  path amp err   : {m.get('amplitude_error_db', float('nan')):.2f} dB")
        print(f"  path corr      : {m.get('correlation', float('nan')):.4f}")
    else:
        print("  (no path metrics)")
    # top-line path sanity independent of the metric dict
    h = algo.get_echo_path()
    pk = int(np.argmax(np.abs(h)))
    print(f"  learned peak   : {np.abs(h[pk]):.4f} @ {pk} samples "
          f"(true 0.60 @ 720)")
    return result


def main(only: Optional[str] = None):
    here = os.path.dirname(os.path.abspath(__file__))
    gt_json = os.path.join(here, 'ground_truth_echo_path.json')
    if not os.path.exists(gt_json):
        print("Ground truth missing — running echo_path_data.py first...")
        os.system(f'"{sys.executable}" echo_path_data.py')

    data = load_echo_path_data(gt_json)
    true_path = data.impulse_response
    ref, sr = sf.read(os.path.join(here, 'ground_truth_reference.wav'))
    mic, _ = sf.read(os.path.join(here, 'ground_truth_echo.wav'))
    print(f"ground truth: {len(true_path)}-tap path, delay "
          f"{data.params.initial_delay_samples} samples "
          f"({data.params.initial_delay_samples / 16.0:.1f} ms); "
          f"signals {len(ref)} samples ({len(ref)/sr:.1f} s)")

    runs = []
    if only in (None, 'fdnlms'):
        runs.append(('FD_NLMS  (classic [0;e] + G + gate)',
                     lambda: FDNLMSAdapter(n_g=N_G, fft_size=FFT, step=STEP)))
    if only in (None, 'cgmdf'):
        runs.append(('CG-MDF hop (beta=0.3) + gate',
                     lambda: CGMDFAdapter(n_g=N_G, fft_size=FFT, step=STEP)))
    for tag, make in runs:
        run_algorithm(tag, make, ref, mic, true_path, data)


if __name__ == '__main__':
    main(sys.argv[1].lower() if len(sys.argv) > 1 else None)
